"""Standalone HTML report generation with embedded styling."""

from pathlib import Path

from agentbench.runner import BenchmarkReport

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AgentBench Report — {suite_name}</title>
<style>
  {{"{{"}}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 960px; margin: 0 auto; padding: 24px; background: #f8f9fa; color: #1a1a2e; }}
    h1 {{ font-size: 1.8em; margin-bottom: 4px; }}
    .subtitle {{ color: #6c757d; margin-top: 0; }}
    .meta {{ display: flex; gap: 24px; flex-wrap: wrap; margin: 20px 0; padding: 16px; background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
    .meta-item {{ }}
    .meta-label {{ font-size: 0.75em; color: #6c757d; text-transform: uppercase; letter-spacing: 0.05em; }}
    .meta-value {{ font-size: 1.2em; font-weight: 600; }}
    .score-circle {{ display: inline-flex; align-items: center; justify-content: center; width: 80px; height: 80px; border-radius: 50%; font-size: 1.5em; font-weight: 700; color: white; }}
    .score-green {{ background: #2d9b4e; }}
    .score-yellow {{ background: #e6a817; }}
    .score-red {{ background: #d63939; }}
    .summary-bar {{ height: 24px; border-radius: 12px; background: #e9ecef; overflow: hidden; margin: 16px 0; }}
    .summary-fill {{ height: 100%; border-radius: 12px; transition: width 0.8s ease; }}
    table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
    th {{ background: #1a1a2e; color: white; padding: 12px 16px; text-align: left; font-weight: 500; }}
    td {{ padding: 10px 16px; border-bottom: 1px solid #eee; }}
    tr:last-child td {{ border-bottom: none; }}
    .pass {{ color: #2d9b4e; font-weight: 600; }}
    .fail {{ color: #d63939; font-weight: 600; }}
    .tag {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75em; background: #e7f5ff; color: #1971c2; margin: 1px; }}
    .footer {{ margin-top: 32px; font-size: 0.8em; color: #6c757d; text-align: center; }}
  }}
</style>
</head>
<body>
  <h1>AgentBench Report</h1>
  <p class="subtitle">{suite_name} — {agent_name}</p>

  <div class="meta">
    <div class="meta-item">
      <div class="meta-label">Overall Score</div>
      <div class="score-circle score-{score_color}">{overall_pct:.0f}%</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Passed</div>
      <div class="meta-value">{passed}/{total}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Duration</div>
      <div class="meta-value">{duration_ms:.0f} ms</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Cost</div>
      <div class="meta-value">${cost:.6f}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Timestamp</div>
      <div class="meta-value">{timestamp}</div>
    </div>
  </div>

  <div class="summary-bar">
    <div class="summary-fill" style="width: {overall_pct:.0f}%; background: {bar_color};"></div>
  </div>

  <table>
    <thead>
      <tr><th>ID</th><th>Task</th><th>Tags</th><th>Score</th><th>Status</th><th>Duration</th></tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <div class="footer">Generated by AgentBench v0.1.0</div>
</body>
</html>
"""


def generate_html_report(report: BenchmarkReport, output_path: str | Path) -> Path:
    """Generate a standalone HTML report and write it to *output_path*.

    Returns the path to the generated file.
    """
    pct = report.overall_percentage

    if pct >= 80:
        score_color = "green"
        bar_color = "#2d9b4e"
    elif pct >= 50:
        score_color = "yellow"
        bar_color = "#e6a817"
    else:
        score_color = "red"
        bar_color = "#d63939"

    rows = ""
    for r in report.results:
        status_class = "pass" if r.score.passed else "fail"
        status_text = "PASS" if r.score.passed else "FAIL"
        score_display = f"{r.score.percentage:.0f}%" if r.score.max_score > 0 else "-"
        tags_html = " ".join(f'<span class="tag">{t}</span>' for t in r.task.tags[:3])
        rows += (
            f"<tr>"
            f"<td>{r.task.id}</td>"
            f"<td>{r.task.name}</td>"
            f"<td>{tags_html}</td>"
            f"<td>{score_display}</td>"
            f"<td class=\"{status_class}\">{status_text}</td>"
            f"<td>{r.duration_ms:.0f}ms</td>"
            f"</tr>\n"
        )

    html = _HTML_TEMPLATE.format(
        suite_name=report.suite_name,
        agent_name=report.agent_name,
        overall_pct=pct,
        score_color=score_color,
        bar_color=bar_color,
        passed=report.passed_count,
        total=report.total_count,
        duration_ms=report.total_duration_ms,
        cost=report.total_cost,
        timestamp=report.timestamp,
        rows=rows,
    )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html)
    return output_path
